import { BookOpen, CheckCircle2, PlayCircle } from "lucide-react";
import Image from "next/image";import Link from "next/link";import{redirect}from"next/navigation";
import{BrandMark}from"@/components/brand-mark";import{createAdminClient}from"@/lib/supabase/admin";import{createClient}from"@/lib/supabase/server";import{getStudentAcademyContext}from"@/lib/student-routing";import styles from"./courses.module.css";

export default async function StudentCoursesPage({searchParams}:{searchParams?:Promise<{portal?:string}>}){
 const query=await searchParams;const academy=await getStudentAcademyContext(query?.portal);const supabase=await createClient();if(!supabase)redirect("/login");const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");let aq=supabase.from("student_applications").select("trader_id,portal:portals!inner(portal_name,slug)").eq("student_user_id",user.id).eq("status","verified");if(academy.portalId)aq=aq.eq("portal_id",academy.portalId);if(academy.portalSlug)aq=aq.eq("portal.slug",academy.portalSlug);const{data:app}=await aq.order("verified_at",{ascending:false}).limit(1).maybeSingle();if(!app)redirect(`${academy.basePath}${academy.querySuffix}`);
 const[{data:courseRows},{data:progressRows}]=await Promise.all([supabase.from("courses").select("id,title,description,cover_path,sort_order,lessons(id,is_required,status)").eq("trader_id",app.trader_id).eq("status","published").order("sort_order"),supabase.from("lesson_progress").select("course_id,lesson_id,position_seconds,is_started,is_completed,last_activity_at").eq("trader_id",app.trader_id).eq("student_user_id",user.id)]);
 const admin=createAdminClient();const courses=await Promise.all((courseRows??[]).map(async c=>{const required=(c.lessons??[]).filter(l=>l.status==="published"&&l.is_required);const progress=(progressRows??[]).filter(p=>p.course_id===c.id);const complete=required.filter(l=>progress.some(p=>p.lesson_id===l.id&&p.is_completed)).length;let thumbnailUrl:null|string=null;if(c.cover_path&&admin){const{data:signed}=await admin.storage.from("course-content").createSignedUrl(c.cover_path,300);thumbnailUrl=signed?.signedUrl??null}return{...c,thumbnailUrl,lessonCount:required.length,percent:required.length?Math.round(complete/required.length*100):0,complete:required.length>0&&complete===required.length,lastActivity:progress.map(p=>p.last_activity_at).sort().at(-1)??null,resume:progress.filter(p=>p.is_started&&!p.is_completed).sort((a,b)=>(b.last_activity_at??"").localeCompare(a.last_activity_at??""))[0]??null}}));
 const continueCourse=courses.filter(c=>c.resume&&!c.complete).sort((a,b)=>(b.lastActivity??"").localeCompare(a.lastActivity??""))[0];const completed=courses.filter(c=>c.complete);const portal=Array.isArray(app.portal)?app.portal[0]:app.portal;const base=academy.basePath;const suffix=academy.querySuffix;
 const card=(course:typeof courses[number])=><Link className={styles.course} href={`${base}/courses/${course.id}${suffix}`} key={course.id}><div className={styles.thumbnail}>{course.thumbnailUrl?<Image alt="" fill sizes="(max-width:600px) 100vw,360px" src={course.thumbnailUrl} unoptimized/>:<BookOpen/>}</div><div className={styles.courseBody}><h2>{course.title}</h2><p>{course.description||"Structured academy course"}</p><div className={styles.percent}><span style={{width:`${course.percent}%`}}/></div><strong>{course.percent}% · {course.lessonCount} required lessons</strong></div></Link>;
 return <main className={styles.page}><nav className={styles.nav}><BrandMark href={`${base}/courses${suffix}`} label={base==="/academy"?portal?.portal_name??"Academy":"KaiMentors"}/><div className={styles.navActions}><Link href={`${base}/messages${suffix}`}>Messages</Link><Link href={`${base}${suffix}`}>Access status</Link><Link href="/auth/signout">Sign out</Link></div></nav><header className={styles.header}><p className="eyebrow">{portal?.portal_name??"Mentor academy"}</p><h1>My Learning</h1><p>Resume protected lessons, track your progress, and revisit completed courses.</p></header>
 {continueCourse?<section className={`${styles.content} ${styles.learningSection}`}><div className={styles.sectionTitle}><div><p className="eyebrow">Continue Watching</p><h2>Pick up where you left off</h2></div><Link href={`${base}/courses/${continueCourse.id}/lessons/${continueCourse.resume!.lesson_id}${suffix}`}><PlayCircle/> Resume lesson</Link></div>{card(continueCourse)}</section>:null}
 <section className={`${styles.content} ${styles.learningSection}`}><div className={styles.sectionTitle}><div><p className="eyebrow">Library</p><h2>Available courses</h2></div></div>{courses.length?<div className={styles.grid}>{courses.map(card)}</div>:<div className={styles.empty}><BookOpen/><h2>No available courses</h2><p>Your mentor is preparing the learning library or access has not been assigned.</p></div>}</section>
 {completed.length?<section className={`${styles.content} ${styles.learningSection}`}><div className={styles.sectionTitle}><div><p className="eyebrow">Completed</p><h2><CheckCircle2/> Finished courses</h2></div></div><div className={styles.grid}>{completed.map(card)}</div></section>:null}</main>
}
